creator_config:
  min_total_coins: 0
  max_total_coins: 1000

  min_median_market_cap: 0
  min_trader_pnl_average: 10
  min_total_holders_average: 0
  min_average_volume: 0
  min_median_total_trades: 0

  min_average_unique_buy_to_sell_ratio: 0
  min_average_buy_trader_size: 0

ws_port: 1661
http_port: 1662
start_balance_sol: 12321.0

buy_config:
  amount_sol: 0.6
  tp1_pct: 15.0
  tp1_sell_pct: 30.0
  tp2_pct: 50.0
  tp2_sell_pct: 50.0
  exit_profit_floor: -20.0
  time_kill_secs: 25
  time_kill_min_profit_pct: 10.0
  trailing_stop_drawdown_pct: 30.0
